openapi: 3.0.0
info:
  title: U MESSE API
  description: U MESSE API
  version: 0.0.1
servers:
- url: /api
paths:
  /ping:
    get:
      tags:
      - ping
      summary: ping
      operationId: pingGET
      responses:
        default:
          description: successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_default'
      x-swagger-router-controller: Ping
  /auth:
    post:
      tags:
      - auth
      summary: 端末認証
      operationId: authPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        "200":
          description: 端末認証
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'
      x-swagger-router-controller: Auth
  /user:
    get:
      tags:
      - user
      summary: User情報取得
      operationId: userGET
      responses:
        "200":
          description: User情報
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      x-swagger-router-controller: User
  /user/cm:
    get:
      tags:
      - cm
      summary: CMリスト取得
      operationId: userCmGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CmItem'
                x-content-type: application/json
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Cm
    post:
      tags:
      - cm
      summary: CM新規結合
      operationId: userCmPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_1'
      responses:
        "200":
          description: successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CmItem'
        default:
          description: Default error sample response
      x-swagger-router-controller: Cm
  /user/cm/{cmId}:
    get:
      tags:
      - cm
      summary: CM情報取得
      operationId: userCmCmIdGET
      parameters:
      - name: cmId
        in: path
        description: ID of cm to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CmItem'
                x-content-type: application/json
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Cm
    post:
      tags:
      - cm
      summary: CM情報更新
      operationId: userCmCmIdPOST
      parameters:
      - name: cmId
        in: path
        description: ID of cm to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_2'
      responses:
        default:
          description: Default response
      x-swagger-router-controller: Cm
    delete:
      tags:
      - cm
      summary: CM情報削除
      operationId: userCmCmIdDELETE
      parameters:
      - name: cmId
        in: path
        description: ID of cm to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Cm
  /center/{cmId}:
    post:
      tags:
      - center
      summary: CMセンター連携追加
      operationId: centerCmIdPOST
      parameters:
      - name: cmId
        in: path
        description: ID of cm to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_3'
      responses:
        default:
          description: Default response
      x-swagger-router-controller: Center
    delete:
      tags:
      - center
      summary: CMセンター連携削除
      operationId: centerCmIdDELETE
      parameters:
      - name: cmId
        in: path
        description: ID of cm to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Center
  /center/download:
    get:
      tags:
      - center
      summary: センターCM連携（センター専用）
      operationId: centerDownloadGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Center
  /center/download/{cmId}:
    post:
      tags:
      - center
      summary: センターCM連携完了（センター専用）
      operationId: centerDownloadCmIdPOST
      parameters:
      - name: cmId
        in: path
        description: ID of cm to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Center
  /shear:
    get:
      tags:
      - shear
      summary: CM共有リスト取得
      operationId: shearGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CmItem'
                x-content-type: application/json
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Shear
  /shear/{cmId}:
    post:
      tags:
      - shear
      summary: CM共有追加
      operationId: shearCmIdPOST
      parameters:
      - name: cmId
        in: path
        description: ID of cm to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        default:
          description: Default response
      x-swagger-router-controller: Shear
    delete:
      tags:
      - shear
      summary: CM共有削除
      operationId: shearCmIdDELETE
      parameters:
      - name: cmId
        in: path
        description: ID of cm to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Shear
  /user/recording:
    get:
      tags:
      - recording
      summary: 録音データリスト取得
      operationId: userRecordingGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
      x-swagger-router-controller: Recording
    post:
      tags:
      - recording
      summary: 新規録音データ
      operationId: userRecordingPOST
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/body_4'
      responses:
        "200":
          description: successful
      x-swagger-router-controller: Recording
  /user/recording/{recordingId}:
    get:
      tags:
      - recording
      summary: 録音データ取得
      operationId: userRecordingRecordingIdGET
      parameters:
      - name: recordingId
        in: path
        description: ID of recording to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        default:
          description: Default response
      x-swagger-router-controller: Recording
    post:
      tags:
      - recording
      summary: 録音データ更新（メタデータのみ）
      operationId: userRecordingRecordingIdPOST
      parameters:
      - name: recordingId
        in: path
        description: ID of recording to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/body_5'
      responses:
        "200":
          description: successful
      x-swagger-router-controller: Recording
    delete:
      tags:
      - recording
      summary: 録音データ削除
      operationId: userRecordingRecordingIdDELETE
      parameters:
      - name: recordingId
        in: path
        description: ID of recording to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        default:
          description: Default response
      x-swagger-router-controller: Recording
  /user/tts:
    get:
      tags:
      - tts
      summary: TTSデータリスト取得
      operationId: userTtsGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
      x-swagger-router-controller: Tts
    post:
      tags:
      - tts
      summary: 新規録音データ
      operationId: userTtsPOST
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/body_6'
      responses:
        "200":
          description: successful
      x-swagger-router-controller: Tts
  /user/tts/{ttsId}:
    get:
      tags:
      - tts
      summary: TTSデータ取得
      operationId: userTtsTtsIdGET
      parameters:
      - name: ttsId
        in: path
        description: ID of tts to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        default:
          description: Default response
      x-swagger-router-controller: Tts
    post:
      tags:
      - tts
      summary: TTSデータ更新（メタデータのみ）
      operationId: userTtsTtsIdPOST
      parameters:
      - name: ttsId
        in: path
        description: ID of tts to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/body_7'
      responses:
        "200":
          description: successful
      x-swagger-router-controller: Tts
    delete:
      tags:
      - tts
      summary: TTSデータ削除
      operationId: userTtsTtsIdDELETE
      parameters:
      - name: ttsId
        in: path
        description: ID of tts to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: string
      responses:
        default:
          description: Default response
      x-swagger-router-controller: Tts
  /bgm:
    get:
      tags:
      - resources
      summary: BGM
      operationId: bgmGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Resources
  /narration:
    get:
      tags:
      - resources
      summary: ナレーション
      operationId: narrationGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Resources
  /chime:
    get:
      tags:
      - resources
      summary: Open/Endチャイム
      operationId: chimeGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Resources
  /tts:
    get:
      tags:
      - resources
      summary: TTSテンプレート一覧
      operationId: ttsGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Resources
  /signedUrl:
    get:
      tags:
      - s3
      summary: S3オブジェクトの署名付きURLの取得
      description: 試聴再生、録音音声アップロード
      operationId: signedUrlGET
      responses:
        "200":
          description: The response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
        "400":
          description: Response invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: S3
components:
  schemas:
    Auth:
      properties:
        token:
          type: string
          example: "1234567890"
      example:
        token: "1234567890"
    User:
      properties:
        unisCustomerCd:
          type: string
          example: "1234567890"
        customerName:
          type: string
          example: Meguro Cafe
        customerGroupCd:
          type: string
          example: "1234567890"
        customerGroupName:
          type: string
          example: USEN
      example:
        customerGroupName: USEN
        unisCustomerCd: "1234567890"
        customerName: Meguro Cafe
        customerGroupCd: "1234567890"
    CmItem:
      properties:
        id:
          type: integer
        name:
          type: string
        detail:
          type: string
      example:
        name: name
        id: 0
        detail: detail
    BgmItem:
      properties:
        id:
          type: integer
        name:
          type: string
        detail:
          type: string
      example:
        name: name
        id: 0
        detail: detail
    NarrationItem:
      properties:
        id:
          type: integer
        name:
          type: string
        detail:
          type: string
      example:
        name: name
        id: 0
        detail: detail
    ChimeItem:
      properties:
        id:
          type: integer
        name:
          type: string
        detail:
          type: string
      example:
        name: name
        id: 0
        detail: detail
    RecordingItem:
      properties:
        id:
          type: integer
        title:
          type: string
        detail:
          type: string
      example:
        id: 0
        detail: detail
        title: title
    TtsItem:
      properties:
        id:
          type: integer
        title:
          type: string
        detail:
          type: string
      example:
        id: 0
        detail: detail
        title: title
    CenterItem:
      properties:
        id:
          type: integer
        title:
          type: string
        detail:
          type: string
      example:
        id: 0
        detail: detail
        title: title
    Error:
      type: object
      properties:
        status:
          type: string
        code:
          type: string
        title:
          type: string
        detail:
          type: string
      description: Error
    inline_response_default:
      properties:
        message:
          type: string
          example: ok
      example:
        message: ok
    body:
      type: object
      properties:
        unis_customer_cd:
          type: string
    usercm_narration:
      type: object
      properties:
        narrationId:
          type: string
        volume:
          type: integer
          format: int64
    usercm_startChime:
      type: object
      properties:
        startChimeId:
          type: string
        volume:
          type: integer
          format: int64
    usercm_endChime:
      type: object
      properties:
        endChimeId:
          type: string
        volume:
          type: integer
          format: int64
    usercm_bgm:
      type: object
      properties:
        bgmId:
          type: string
        volume:
          type: integer
          format: int64
    body_1:
      type: object
      properties:
        narration:
          type: array
          items:
            $ref: '#/components/schemas/usercm_narration'
        startChime:
          $ref: '#/components/schemas/usercm_startChime'
        endChime:
          $ref: '#/components/schemas/usercm_endChime'
        bgm:
          $ref: '#/components/schemas/usercm_bgm'
    body_2:
      type: object
      properties:
        title:
          type: string
          example: タイトル
        description:
          type: string
          example: 説明文
        seconds:
          type: integer
          format: int64
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        shear:
          type: boolean
          example: false
        center:
          type: boolean
          example: true
    body_3:
      type: object
      properties:
        title:
          type: string
          example: タイトル
        description:
          type: string
          example: 説明文
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
    inline_response_200:
      properties:
        value:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/CenterItem'
      example:
        data:
        - id: 0
          detail: detail
          title: title
        - id: 0
          detail: detail
          title: title
        value: value
    inline_response_200_1:
      properties:
        value:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/RecordingItem'
      example:
        data:
        - id: 0
          detail: detail
          title: title
        - id: 0
          detail: detail
          title: title
        value: value
    body_4:
      type: object
      properties:
        filename:
          type: string
        recordedFile:
          type: string
          format: binary
    body_5:
      type: object
      properties:
        filename:
          type: string
        recordedFile:
          type: string
          format: binary
    inline_response_200_2:
      properties:
        value:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/TtsItem'
      example:
        data:
        - id: 0
          detail: detail
          title: title
        - id: 0
          detail: detail
          title: title
        value: value
    body_6:
      type: object
      properties:
        filename:
          type: string
        recordedFile:
          type: string
          format: binary
    body_7:
      type: object
      properties:
        filename:
          type: string
        recordedFile:
          type: string
          format: binary
    inline_response_200_3:
      properties:
        value:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/BgmItem'
      example:
        data:
        - name: name
          id: 0
          detail: detail
        - name: name
          id: 0
          detail: detail
        value: value
    inline_response_200_4:
      properties:
        value:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/NarrationItem'
      example:
        data:
        - name: name
          id: 0
          detail: detail
        - name: name
          id: 0
          detail: detail
        value: value
    inline_response_200_5:
      properties:
        value:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/ChimeItem'
      example:
        data:
        - name: name
          id: 0
          detail: detail
        - name: name
          id: 0
          detail: detail
        value: value
    inline_response_200_6:
      properties:
        url:
          type: string
      example:
        url: url
  parameters:
    CmId:
      name: cmId
      in: path
      description: ID of cm to return
      required: true
      style: simple
      explode: false
      schema:
        type: string
        format: string
    RecordingId:
      name: recordingId
      in: path
      description: ID of recording to return
      required: true
      style: simple
      explode: false
      schema:
        type: string
        format: string
    TtsId:
      name: ttsId
      in: path
      description: ID of tts to return
      required: true
      style: simple
      explode: false
      schema:
        type: string
        format: string
